// tests/cases/ct_asm_k1_base64url holds base64url's character maps, and one
// group each way, to the assembly check. The copy is what the check reads and
// the module is what runs, so this holds each copy to `nish/crypto/base64url`
// through its public functions: the character of every sextet, the sextet (or
// refusal) of every byte, and generated groups both ways.
import { base64urlDecode, base64urlEncode } from "nish/crypto/base64url";
import { Suite } from "nish/testing";
import {
  base64urlCharOf,
  base64urlDecodeGroup,
  base64urlEncodeGroup,
  base64urlSextetOf,
} from "../../cases/ct_asm_k1_base64url";

/** xorshift32 (Marsaglia, 2003): a fixed stream of test bytes, not a secret. */
const nextByte = (state: u32[]): u8 => {
  let x: u32 = state[0];
  x = x ^ (x << toU32(13));
  x = x ^ (x >>> toU32(17));
  x = x ^ (x << toU32(5));
  state[0] = x;
  return toU8(x >>> toU32(24));
};

/** The bytes of `text`, as the copies take a group. */
const bytesOf = (text: string): u8[] => {
  const out: u8[] = [];
  for (let i: i32 = 0; i < toI32(text.length); i++) {
    out.push(toU8(text.charCodeAt(i)));
  }
  return out;
};

/** How many sextets the copied `base64urlCharOf` spells differently from `base64urlEncode`. */
const charsDisagree = (): i32 => {
  let differ: i32 = 0;
  for (let v: i32 = 0; v < 64; v++) {
    // [0, 0, v] encodes as "AA" and then the sextets 0 and v.
    const text: string = base64urlEncode([toU8(0), toU8(0), toU8(v)]);
    if (toI32(text.length) !== 4 || toI32(text.charCodeAt(3)) !== base64urlCharOf(v)) {
      differ++;
    }
  }
  return differ;
};

/** How many of the 256 bytes the copied `base64urlSextetOf` reads differently from `base64urlDecode`. */
const sextetsDisagree = (): i32 => {
  let differ: i32 = 0;
  for (let c: i32 = 0; c < 256; c++) {
    const decoded: u8[] | null = base64urlDecode(`AAA${String.fromCharCode(c)}`);
    const v: i32 = base64urlSextetOf(c);
    if (decoded === null) {
      if (v !== -1) {
        differ++;
      }
    } else if (v < 0 || v > 63 || toI32(decoded.length) !== 3 || toI32(decoded[2]) !== v) {
      differ++;
    }
  }
  return differ;
};

/** How many of `rounds` generated three-byte groups the copies encode or decode differently from the module. */
const groupsDisagree = (state: u32[], rounds: i32): i32 => {
  let differ: i32 = 0;
  const chars: u8[] = new Array<u8>(4);
  const back: u8[] = new Array<u8>(3);
  for (let r: i32 = 0; r < rounds; r++) {
    const group: u8[] = [nextByte(state), nextByte(state), nextByte(state)];
    base64urlEncodeGroup(group, chars);
    const text: string = base64urlEncode(group);
    const theirs: u8[] = bytesOf(text);
    let same: boolean = toI32(theirs.length) === 4;
    for (let i: i32 = 0; same && i < 4; i++) {
      same = chars[i] === theirs[i];
    }
    const bad: i32 = base64urlDecodeGroup(theirs, back);
    if (!same || bad !== 0 || back[0] !== group[0] || back[1] !== group[1] || back[2] !== group[2]) {
      differ++;
    }
    // One character replaced by a generated byte: the copy refuses exactly
    // when the module does, and otherwise decodes the same bytes.
    const at: i32 = r & 3;
    theirs[at] = nextByte(state);
    const spelled: string[] = [];
    for (const b of theirs) {
      spelled.push(String.fromCharCode(toI32(b)));
    }
    const decoded: u8[] | null = base64urlDecode(spelled.join(""));
    const refused: boolean = base64urlDecodeGroup(theirs, back) !== 0;
    if (decoded === null) {
      if (!refused) {
        differ++;
      }
    } else if (refused || back[0] !== decoded[0] || back[1] !== decoded[1] || back[2] !== decoded[2]) {
      differ++;
    }
  }
  return differ;
};

export const main = (): i32 => {
  const t = new Suite("base64url k1 copies");
  const state: u32[] = [toU32(0x2545f491)];
  t.eqI32("base64urlCharOf spells every sextet as base64urlEncode does", charsDisagree(), 0);
  t.eqI32("base64urlSextetOf reads every byte as base64urlDecode does", sextetsDisagree(), 0);
  t.eqI32("the group copies agree with the module on 4,000 generated groups", groupsDisagree(state, 4000), 0);
  return t.done();
};
