/* StaticTS runtime ABI, public C header.
 *
 * Include this from C drivers, N-API shims, or any other host that links
 * `runtime/runtime.c` next to compiled StaticTS modules. Everything here is
 * a contract shared with `src/codegen/runtime.ts` (the IR side) and
 * `runtime/runtime.c` (the implementation); `tests/run.js` checks that every
 * runtime function declared in runtime.ts has a prototype in this file.
 *
 * Headers generated by `statictsc --emit-header` include this one, so keep
 * it C11-clean under -Wall -Wextra -Werror and usable from C++.
 */
#ifndef STATICTSC_H
#define STATICTSC_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bind a C declaration to a StaticTS symbol whose name C cannot spell (a
 * keyword such as `double`): `int32_t double_(int32_t n) STS_SYMBOL("double");`
 * Generated headers use it; __USER_LABEL_PREFIX__ supplies the `_` Mach-O adds. */
#define STS_STRINGIFY_(x) #x
#define STS_STRINGIFY(x) STS_STRINGIFY_(x)
#define STS_SYMBOL(name) __asm__(STS_STRINGIFY(__USER_LABEL_PREFIX__) name)

/* ---- Strings ------------------------------------------------------------
 * A StaticTS `string` is a pointer to this header: { u64 len, bytes[len], 0 }.
 * `len` is the UTF-8 byte length (`s.length` in StaticTS). The bytes are
 * NUL-terminated so `s->data` is a valid C string, but they may contain
 * embedded NULs, so prefer `len` over strlen. Strings are immutable: a
 * pointer can be shared freely and never needs copying.
 *
 * Literals live in the module's constant data; every other string is
 * allocated in the arena and stays valid until `sts_reset_arena` or
 * `sts_free_arena`. Never free a string yourself. */
typedef struct sts_str {
  uint64_t len;
  char data[];
} sts_str;

/* ---- Arena --------------------------------------------------------------
 * One global bump allocator. Compiled modules read this struct directly
 * (the fast path is inlined into the IR), so its layout is ABI:
 *   %struct.sts_arena = type { i8*, i64, i64, i8* }
 * Fields: current chunk buffer, bump offset, chunk capacity, chunk list. */
struct sts_arena {
  char *buf;
  size_t off;
  size_t cap;
  void *chunks;
};
extern struct sts_arena sts_arena;

/* Bump allocation: 8-byte rounded and aligned, uninitialised. */
void *sts_alloc_struct(size_t size);
/* Slow path: push a new chunk (at least 64 KB) and bump from it. Called by
 * the inlined fast path when the current chunk is full; rarely by hosts. */
void *sts_arena_grow(size_t size);
/* Recycle everything in O(1): keeps the newest chunk, frees the rest. Every
 * arena string and object becomes invalid. Call it between batches. */
void sts_reset_arena(void);
/* Release every chunk. The arena is lazy, so it can be used again afterwards. */
void sts_free_arena(void);

/* ---- String operations ------------------------------------------------- */
/* Copy `len` bytes into a new arena string (`bytes` need not be terminated). */
sts_str *sts_str_new(const char *bytes, uint64_t len);
/* `a + b` */
sts_str *sts_str_concat(const sts_str *a, const sts_str *b);
/* `a === b`: same bytes (pointer equality is a fast path, not a requirement). */
bool sts_str_eq(const sts_str *a, const sts_str *b);
/* `s.length`: the byte length. Compiled code loads the header directly. */
uint64_t sts_str_len(const sts_str *s);
/* `console.log(s)`: one write(2) of the bytes plus a newline to stdout. */
void sts_print(const sts_str *s);
/* Number to string, as `${n}` does: decimal for i32, `%.17g` for f64. */
sts_str *sts_str_from_i32(int32_t v);
sts_str *sts_str_from_f64(double v);

#ifdef __cplusplus
}
#endif

#endif /* STATICTSC_H */
