/**
 * The checked-in successors to the four oracles that die with stage0
 * (WP19 gate G2.4, `docs/wp19-stage0-retirement.md` §2B and §3).
 *
 *   node tests/self/goldens.js                 verify all four against stage1
 *   node tests/self/goldens.js checked         just one of them
 *   node tests/self/goldens.js --update        rewrite the goldens from stage1
 *   node tests/self/goldens.js --seed <nish>   the compiler that builds stage1
 *   node tests/self/goldens.js --verbose --lines 40
 *
 * `checked_oracle.js`, `types_oracle.js`, `diagnostics_oracle.js` and
 * `symbols_oracle.js` each prove stage1 correct by comparing it with stage0.
 * The day `src/` is deleted they prove nothing, because the thing they compare
 * against is gone. They are green today, which is the whole opportunity: the
 * two implementations agree, so stage1's output *is* the agreed behaviour, and
 * writing it down keeps it past stage0's death.
 *
 * So this tool records the same four outputs as goldens and compares stage1's
 * live output against them. It names neither `src/` nor `dist/` anywhere, and
 * the only compiler it runs is one it builds out of `self/` — which is why it
 * still works in a tree where stage0 has been deleted. The four oracles keep
 * running beside it for as long as stage0 lives; nothing here replaces them
 * while they can still say something this cannot.
 *
 * **The seed.** Building stage1 takes a compiler, and after retirement that is
 * the last released `nish` (G3). The seed is `--seed`, then `NISH_BOOTSTRAP` —
 * the variable `scripts/bootstrap.sh` reads — then `build/nish`, what
 * `npm run bootstrap` leaves behind; `tests/self/seed.js` resolves it, and the
 * four oracles that outlive stage0 now build their binaries the same way.
 * There is deliberately no fourth answer *here*: a tool that reached for
 * stage0 when it found nothing would be exactly the dependency this gate
 * exists to remove. `tests/run.js` passes today's seed in with `--seed`,
 * because the *suite* still has stage0 and this tool must not.
 *
 * **What each golden holds.**
 *
 *   - `goldens/checked.txt` — `--emit-checked` for every positive program of
 *     the corpus outside `self/`: 262 programs, whole dumps, one after
 *     another. This is where per-construct checker coverage lives, so it is
 *     stored as text a failure can be read as a diff.
 *   - `goldens/checked_self.txt` — the same dump for the 57 programs of
 *     `self/`, stored **deduplicated by module**. A `self/` program is loaded
 *     whole, so each of the 57 entries re-dumps every module it imports, and
 *     the raw text is 19.9 MB of which 1.0 MB is distinct. The entry index
 *     records each program's module load order and each module's section is
 *     written once. Nothing is measured out: the check still runs all 57
 *     programs and compares every byte they print, and a module whose dump
 *     differs between two entries is a hard error rather than a silent pick.
 *   - `goldens/types.txt`, `goldens/diagnostics.txt`, `goldens/symbols.txt` —
 *     the stdout of the three driver programs the dying oracles run
 *     (`tests/self/types.ts` and friends), which is the whole of what those
 *     oracles compare.
 *
 * A golden is regenerated by `npm run test:update`, the same command that
 * writes a missing `.ll`, or by `--update` here. Regenerate it from stage1 and
 * never from stage0: stage1 is what survives, and the existing oracles are
 * what say the two agree.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { checkerArgs, programs, root } from "./corpus.js";
// The seed resolution is shared with the four oracles that survive stage0
// (WP19 G2.3), and `defaultSeedSpec` is where this file's rule lives: three
// answers and no fourth, because a tool that reached for stage0 would be the
// dependency the gate exists to remove.
import { defaultSeedSpec, resolveSeed, spawnSeed } from "./seed.js";

const GOLDENS = path.join(root, "tests", "self", "goldens");
const BUILD = path.join(root, "build", "self", "goldens");

/** Long dump lines are cut to this in a failure report, so a diff stays readable. */
const MAX_LINE = 160;

/** The first diagnostic of a compiler's stderr, without its file:line:col prefix. */
function firstLine(output) {
  const line = output.trim().split("\n")[0] ?? "";
  return line.replace(/^[^:]*:\d+:\d+: /, "");
}

/**
 * One stage1 program, built out of live sources by the seed. The binaries land
 * under `build/` and are rebuilt on every run: a golden compared against a
 * stale binary is a golden comparing itself with yesterday.
 */
function link(seed, source, stem) {
  const out = path.join(BUILD, stem);
  fs.mkdirSync(BUILD, { recursive: true });
  const built = spawnSeed(seed, [path.join(root, source), "--link", out]);
  if (built.status !== 0) return { error: `${seed.label} could not build ${source}:\n${built.stderr}` };
  return {
    run: (args) => spawnSync(out, args, { cwd: root, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 }),
  };
}

/**
 * The dump's lines, blanks dropped — `checked_oracle.js`'s normalisation —
 * with `self/branding.ts`'s folded `VERSION` replaced by a placeholder.
 *
 * The checker folds module constants, so the dump records `VERSION`'s value,
 * which is the compiler's version and changes at every release. Pinning it
 * would mean the release pull request — the commit whose whole job is to bump
 * the version — turns this golden red at itself. That the constant is folded
 * at all is still pinned here, by this line's shape and by every other module
 * constant in the corpus; only the digits are let go. `tests/run.js` does the
 * same to the DWARF producer, for the same reason.
 */
function dumpLines(dump) {
  return dump
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => line.replace(/^(const VERSION: string = )"[^"]*"/, '$1"<version>"'));
}

/** `tests/cases/add.ts --number-mode f64`: the program as its record names it. */
function programLabel(named, flags) {
  return flags.length > 0 ? `${named} ${flags.join(" ")}` : named;
}

function header(what) {
  return [
    `# ${what}`,
    "# Generated from stage1 by `npm run test:update` (or `node tests/self/goldens.js --update`).",
    "# WP19 gate G2.4: the coverage that dies with stage0, written down. Do not edit by hand.",
  ];
}

/**
 * `--emit-checked` over the whole corpus, in two files: the construct corpus
 * as whole dumps, and `self/` deduplicated by module.
 *
 * The split is a measurement rather than a taste. The corpus outside `self/`
 * dumps 272 KiB over 262 programs and every byte of it is a construct's
 * layout, signature or folded constant — the material a failure has to be
 * readable as. `self/` dumps 19.9 MB over 57 programs and only 1.0 MB of that
 * is distinct, because every entry re-dumps its imports: storing it whole
 * would multiply one edit to one module by the 57 entries that import it, and
 * a golden nobody can read the diff of is a hash with extra bytes.
 */
function produceChecked(seed) {
  const dumper = link(seed, path.join("self", "dump_checked.ts"), "dump_checked");
  if (dumper.error !== undefined) return { error: dumper.error };

  const outside = [];
  const entries = [];
  const bodies = new Map();
  const bodyOwner = new Map();
  let outsidePrograms = 0;
  let outsideLines = 0;
  let selfPrograms = 0;
  let selfLines = 0;

  for (const file of programs()) {
    const named = path.relative(root, file).split(path.sep).join("/");
    const flags = checkerArgs(file);
    const isSelf = named.startsWith("self/");
    const result = dumper.run([...flags, named]);
    if (result.status !== 0) {
      // A program the checker refuses has no dump, and the reason it gives is
      // a diagnostic wording nothing else here would pin. It belongs in the
      // record for the same reason the dump does.
      const record = `reject ${programLabel(named, flags)}: ${firstLine(result.stderr)}`;
      if (isSelf) entries.push(record);
      else outside.push(record);
      continue;
    }
    const lines = dumpLines(result.stdout);
    if (!isSelf) {
      outsidePrograms++;
      outsideLines += lines.length;
      outside.push(`program ${programLabel(named, flags)}`, ...lines);
      continue;
    }
    selfPrograms++;
    selfLines += lines.length;
    const order = [];
    let module = null;
    let body = [];
    const close = () => {
      if (module === null) return;
      order.push(module);
      const text = body.join("\n");
      const seen = bodies.get(module);
      if (seen === undefined) {
        bodies.set(module, text);
        bodyOwner.set(module, named);
        return;
      }
      if (seen !== text) {
        // Deduplication is only sound while a module dumps the same under
        // every entry that loads it. It does today; the day it stops, the
        // golden has to grow a dimension rather than quietly pick a winner.
        return `module ${module} dumps differently under ${bodyOwner.get(module)} and ${named}`;
      }
      return;
    };
    let conflict;
    for (const line of lines) {
      const at = /^module (\S+)(?: \(entry\))?$/.exec(line);
      if (at !== null) {
        conflict = close() ?? conflict;
        module = at[1];
        body = [];
      } else if (module !== null) {
        body.push(line);
      }
    }
    conflict = close() ?? conflict;
    if (conflict !== undefined) return { error: conflict };
    entries.push(`entry ${programLabel(named, flags)}: ${order.join(" ")}`);
  }

  const selfText = [
    ...header("`--emit-checked` for the 57 programs of `self/`, deduplicated by module."),
    "#",
    "# An `entry` line is one program and the modules it loaded, in load order; the",
    "# entry module is the one the line is named for. A `module` section is that",
    "# module's dump, written once for the whole corpus because it is the same text",
    "# under every entry that loads it — which the generator checks rather than",
    "# assumes. The comparison still runs all 57 programs and reads every byte.",
    `# ${selfPrograms} programs, ${selfLines} dump lines live, ${bodies.size} distinct modules.`,
    ...entries,
  ];
  for (const [module, text] of bodies) {
    selfText.push(`module ${module}`);
    if (text.length > 0) selfText.push(text);
  }

  const outsideText = [
    ...header("`--emit-checked` for every positive program of the corpus outside `self/`."),
    "#",
    "# One `program` record per program, holding its whole dump: every struct's",
    "# layout with field indices and byte offsets, every signature, every folded",
    "# constant, every local and callee of every body, the attribute pass's facts,",
    "# and the order they come out in. A `reject` record is a program the checker",
    "# refuses, and pins the wording it refuses it with.",
    `# ${outsidePrograms} programs, ${outsideLines} dump lines.`,
    ...outside,
  ];

  return {
    files: new Map([
      ["checked.txt", `${outsideText.join("\n")}\n`],
      ["checked_self.txt", `${selfText.join("\n")}\n`],
    ]),
    note: `${outsidePrograms + selfPrograms} programs, ${outsideLines + selfLines} dump lines`,
  };
}

/**
 * One of the three driver programs the dying oracles run. Their stdout is the
 * whole of what those oracles compare — `types_oracle.js` rebuilds it from
 * `dist/types.js` and diffs it line by line — so the stdout is the golden.
 */
function produceDriver(name, source, args, what) {
  return (seed) => {
    const driver = link(seed, source, name);
    if (driver.error !== undefined) return { error: driver.error };
    const run = driver.run(args);
    if (run.status !== 0) return { error: `${name} exited ${run.status}\n${run.stderr}` };
    const lines = run.stdout.split("\n");
    return {
      files: new Map([[`${name}.txt`, `${header(what).join("\n")}\n${run.stdout}`]]),
      note: `${lines.length - 1} lines`,
    };
  };
}

/**
 * The four goldens, each named for the oracle whose coverage it holds. The
 * `oracle` field is what the summary cites, so that a reader of a failure can
 * find the comparison this file was taken from while it still exists.
 */
const GOLDEN_SET = [
  {
    name: "checked",
    oracle: "checked_oracle.js",
    produce: produceChecked,
  },
  {
    name: "types",
    oracle: "types_oracle.js",
    produce: produceDriver(
      "types",
      path.join("tests", "self", "types.ts"),
      [],
      "`self/types.ts` over the type list `tests/self/types.ts` builds: every LLVM type, alignment, printed name, flag and assignable pair."
    ),
  },
  {
    name: "diagnostics",
    oracle: "diagnostics_oracle.js",
    produce: produceDriver(
      "diagnostics",
      path.join("tests", "self", "diagnostics.ts"),
      [
        path.join("tests", "self", "diagnostics_fixture.txt"),
        path.join("tests", "self", "diagnostics_second.txt"),
      ],
      "`self/diagnostics.ts` over the fixtures: the line/column index, every summary line and excerpt, the `--json` object, the sink's order and its `...and N more` cut."
    ),
  },
  {
    name: "symbols",
    oracle: "symbols_oracle.js",
    produce: produceDriver(
      "symbols",
      path.join("tests", "self", "symbols.ts"),
      [],
      "`self/symbols.ts` over the scope script: what each name resolves to, what it reads as, and where every narrowing stops."
    ),
  },
];

/** The first differences between two texts, bounded, with long lines cut. */
function diff(want, got, limit) {
  const a = want.split("\n");
  const b = got.split("\n");
  const out = [];
  const cut = (line) =>
    line === undefined ? "<end of file>" : line.length > MAX_LINE ? `${line.slice(0, MAX_LINE)}...` : line;
  let total = 0;
  let shown = 0;
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] === b[i]) continue;
    total++;
    if (shown < limit) {
      out.push(`  line ${i + 1}:`, `    golden: ${cut(a[i])}`, `    stage1: ${cut(b[i])}`);
      shown++;
    }
  }
  return { total, shown, out };
}

function goldenPath(file) {
  return path.join(GOLDENS, file);
}

/**
 * The seed this file's rule allows: `given` (a `--seed` value), then
 * `NISH_BOOTSTRAP`, then `build/nish`, and no fourth answer. Exported because
 * the oracles that outlive stage0 (`lexer_oracle.js`, `parser_oracle.js`,
 * `support_oracle.js`) follow the same rule since R6 took their stage0
 * fallback away, and one spelling of it is enough.
 */
const seedWithoutStage0 = (given) => {
  const spec = given ?? defaultSeedSpec();
  if (spec === null) {
    return {
      error:
        "no seed compiler: pass --seed <nish>, set NISH_BOOTSTRAP, or run `npm run bootstrap` to leave one in build/nish",
    };
  }
  return resolveSeed(spec);
};

/** `--seed` and `--lines` take a value; everything else is a flag or a golden's name. */
function parse(argv) {
  const options = { update: false, verbose: false, lines: 10, seed: undefined, names: [] };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--update") options.update = true;
    else if (arg === "--verbose") options.verbose = true;
    else if (arg === "--seed") options.seed = argv[++i];
    else if (arg === "--lines") options.lines = Number(argv[++i]);
    else options.names.push(arg);
  }
  return options;
}

function main(argv) {
  const { update, verbose, lines, seed: given, names: named } = parse(argv);
  const limit = verbose ? Number.POSITIVE_INFINITY : lines;
  const wanted = named.length > 0 ? GOLDEN_SET.filter((g) => named.includes(g.name)) : GOLDEN_SET;
  if (wanted.length === 0) {
    process.stderr.write(
      `no such golden: ${named.join(" ")} (have ${GOLDEN_SET.map((g) => g.name).join(", ")})\n`
    );
    return 2;
  }

  const seed = seedWithoutStage0(given);
  if (seed.error !== undefined) {
    process.stderr.write(`${seed.error}\n`);
    return 2;
  }

  fs.mkdirSync(GOLDENS, { recursive: true });
  let failed = 0;
  let bytes = 0;
  const summary = [];
  for (const golden of wanted) {
    const produced = golden.produce(seed);
    if (produced.error !== undefined) {
      process.stdout.write(`  FAIL ${golden.name}: ${produced.error}\n`);
      failed++;
      continue;
    }
    for (const [file, text] of produced.files) {
      const at = goldenPath(file);
      bytes += Buffer.byteLength(text);
      if (update) {
        const before = fs.existsSync(at) ? fs.readFileSync(at, "utf8") : null;
        fs.writeFileSync(at, text);
        summary.push(`${file}: ${before === text ? "unchanged" : before === null ? "written" : "updated"}`);
        continue;
      }
      if (!fs.existsSync(at)) {
        process.stdout.write(`  FAIL ${file} is missing (run with --update to write it)\n`);
        failed++;
        continue;
      }
      const want = fs.readFileSync(at, "utf8");
      if (want === text) {
        summary.push(`${file}: ${golden.name} agrees`);
        continue;
      }
      const d = diff(want, text, limit);
      process.stdout.write(
        `  FAIL ${file}: ${d.total} lines differ from what stage1 prints (${golden.oracle}'s coverage)\n`
      );
      for (const line of d.out) process.stdout.write(`${line}\n`);
      if (d.shown < d.total) {
        process.stdout.write(`  ... and ${d.total - d.shown} more differing lines (--verbose for all)\n`);
      }
      failed++;
    }
    if (produced.note !== undefined && verbose) {
      process.stdout.write(`  ${golden.name}: ${produced.note}\n`);
    }
  }
  // Under `--update` these are the only evidence that a regeneration did or
  // did not move anything, which is the question the person running it has.
  if (verbose) for (const line of summary) process.stdout.write(`  ${line}\n`);

  process.stdout.write(
    `${summary.length} goldens ${update ? "written" : "agree"}, ${failed} failed, ${(bytes / 1024).toFixed(0)} KiB of goldens (seed ${seed.label})\n`
  );
  return failed === 0 ? 0 : 1;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2)));
export { GOLDEN_SET, defaultSeedSpec, resolveSeed, seedWithoutStage0 };
