// tests/cases/ct_asm_k1_ct holds `timingSafeEqual`'s and `timingSafeEqualAt`'s
// loops to the assembly check at fixed tag lengths. The copy is what the check
// reads and the module is what runs, so this holds each copy to
// `nish/crypto/ct` on generated inputs: equal pairs, and pairs with one bit
// flipped at every position, where a copy that drifted from the module would
// answer differently.
import { timingSafeEqual, timingSafeEqualAt } from "nish/crypto/ct";
import { Suite } from "nish/testing";
import { timingSafeEqual32, timingSafeEqual48, timingSafeEqualAt16 } from "../../cases/ct_asm_k1_ct";

/** xorshift32 (Marsaglia, 2003): a fixed stream of test bytes, not a secret. */
const nextByte = (state: u32[]): u8 => {
  let x: u32 = state[0];
  x = x ^ (x << toU32(13));
  x = x ^ (x >>> toU32(17));
  x = x ^ (x << toU32(5));
  state[0] = x;
  return toU8(x >>> toU32(24));
};

/** `n` generated bytes. */
const generated = (state: u32[], n: i32): u8[] => {
  const out: u8[] = [];
  for (let i: i32 = 0; i < n; i++) {
    out.push(nextByte(state));
  }
  return out;
};

/** A fresh copy of `a`. */
const copyOf = (a: u8[]): u8[] => {
  const out: u8[] = [];
  for (const b of a) {
    out.push(b);
  }
  return out;
};

/** A copy of `a` with bit `bit` of byte `at` flipped. */
const flipped = (a: u8[], at: i32, bit: i32): u8[] => {
  const out: u8[] = copyOf(a);
  out[at] = toU8(toI32(out[at]) ^ (1 << bit));
  return out;
};

/**
 * How many comparisons of `len`-byte arrays the fixed-length copy answers
 * differently from `timingSafeEqual`, over an equal pair and every single-bit
 * flip of it, for `rounds` generated arrays.
 */
const wholeDisagree = (state: u32[], len: i32, rounds: i32): i32 => {
  let differ: i32 = 0;
  for (let r: i32 = 0; r < rounds; r++) {
    const a: u8[] = generated(state, len);
    const same: u8[] = copyOf(a);
    const mine: boolean = len === 32 ? timingSafeEqual32(a, same) : timingSafeEqual48(a, same);
    if (mine !== timingSafeEqual(a, same) || !mine) {
      differ++;
    }
    for (let at: i32 = 0; at < len; at++) {
      for (let bit: i32 = 0; bit < 8; bit++) {
        const b: u8[] = flipped(a, at, bit);
        const copy: boolean = len === 32 ? timingSafeEqual32(a, b) : timingSafeEqual48(a, b);
        if (copy !== timingSafeEqual(a, b) || copy) {
          differ++;
        }
      }
    }
  }
  return differ;
};

/** The same for the 16-byte window copy, at generated public offsets. */
const windowDisagree = (state: u32[], rounds: i32): i32 => {
  let differ: i32 = 0;
  for (let r: i32 = 0; r < rounds; r++) {
    const aOff: i32 = toI32(nextByte(state)) & 15;
    const bOff: i32 = toI32(nextByte(state)) & 15;
    const a: u8[] = generated(state, 40);
    const b: u8[] = generated(state, 40);
    for (let k: i32 = 0; k < 16; k++) {
      b[bOff + k] = a[aOff + k];
    }
    const mine: boolean = timingSafeEqualAt16(a, toU16(aOff), b, toU16(bOff));
    if (mine !== timingSafeEqualAt(a, aOff, b, bOff, 16) || !mine) {
      differ++;
    }
    for (let at: i32 = 0; at < 16; at++) {
      const c: u8[] = flipped(b, bOff + at, (at + r) & 7);
      const copy: boolean = timingSafeEqualAt16(a, toU16(aOff), c, toU16(bOff));
      if (copy !== timingSafeEqualAt(a, aOff, c, bOff, 16) || copy) {
        differ++;
      }
    }
  }
  return differ;
};

export const main = (): i32 => {
  const t = new Suite("ct k1 copies");
  const state: u32[] = [toU32(0x1e3779b9)];
  t.eqI32("timingSafeEqual32 agrees with timingSafeEqual on 32-byte tags and every bit flip", wholeDisagree(state, 32, 20), 0);
  t.eqI32("timingSafeEqual48 agrees with timingSafeEqual on 48-byte tags and every bit flip", wholeDisagree(state, 48, 20), 0);
  t.eqI32("timingSafeEqualAt16 agrees with timingSafeEqualAt on 16-byte windows", windowDisagree(state, 200), 0);
  return t.done();
};
