// Exercises check-pr-body.mjs, the CI half of the no-attribution rule: every
// case is [label, the exit code the script should give, the body it is fed,
// the one pattern it should name]. A clean body is exit 0 and names nothing.
//
//   node scripts/check-pr-body.test.mjs
//
// `npm test` runs it. As in `.claude/hooks/no-attribution.test.mjs`, the banned
// strings are built by concatenation so that editing this file, and grepping
// the repository for them, does not turn up a line that reads like the real
// thing.
import { spawnSync } from "node:child_process";
import path from "node:path";

const SCRIPT = path.join(import.meta.dirname, "check-pr-body.mjs");

const COAUTHOR = "a `Co-Authored-By:` trailer naming an agent or a model";
const TRAILER = "a `Claude-Session:` trailer";
const LINK = "a session or assistant link";
const FOOTER = 'a "Generated with ..." footer';
const MODEL = "a model name";

const site = `${"https://"}claude.ai`;

// How #169's body ended when it was opened: its last two lines, then the
// footer the platform appended after the call that created it. The body on
// GitHub has since been edited clean, so this is rebuilt from that footer's
// fixed shape and the session that opened #169 (logged in #162).
const pr169 =
  "Fixes #160\nPart of #162\n\n" +
  `\u{1F916} Generated with [${"Claude"} Code](https://claude.com/claude-code)\n\n` +
  `${site}/code/session_01WBRBnAYYSfbgb4ASoPFXzR`;

const clean =
  "## What changed\n\n- `docs/LANGUAGE.md`: an instantiation is spelled as written.\n\n" +
  "## Checks\n\n- `npm test`: 2299 passed, 0 failed, 1 skipped.\n\nFixes #160\nPart of #162";

const cases = [
  ["ALLOW  a clean body", 0, clean, null],
  ["ALLOW  an empty body", 0, "", null],
  ["ALLOW  no body at all", 0, null, null],
  ["BLOCK  an agent co-author", 1, `Does a thing.\n\nCo-Authored-By: ${"Claude"} <noreply@anthropic.com>`, COAUTHOR],
  ["BLOCK  a session trailer", 1, `Does a thing.\n\n${"Claude"}-Session: session_01P9`, TRAILER],
  ["BLOCK  a session link on its own", 1, `Does a thing.\n\n${site}/code/session_01P9`, LINK],
  ["BLOCK  a generated-by footer", 1, `Does a thing.\n\nGenerated by ${"Claude"}`, FOOTER],
  ["BLOCK  a model name", 1, `Does a thing, written with ${"Claude"} Sonnet.`, MODEL],
  // The prose that describes the rule, which is what this PR's own body is.
  [
    "ALLOW  prose that names the trailer",
    0,
    "Adds a check that fails a body carrying a `Claude-Session:` trailer or a\n" +
      "`claude.ai/code/session_…` link. See `.claude/hooks/attribution-patterns.mjs`.",
    null,
  ],
];

let failed = 0;
const check = (label, ok, detail) => {
  if (!ok) failed++;
  console.log(`${ok ? "pass" : "FAIL"}  ${label}${ok ? "" : `\n${detail.replace(/^/gm, "        ")}`}`);
};

const run = (body) => {
  const env = { ...process.env };
  delete env.BODY;
  if (body !== null) env.BODY = body;
  return spawnSync(process.execPath, [SCRIPT], { env, encoding: "utf8" });
};

// Each case names exactly the pattern it is about, so a sample that starts
// tripping a second pattern shows up here rather than passing on the wrong one.
for (const [label, expected, body, pattern] of cases) {
  const r = run(body);
  const named = r.stderr.split("\n").filter((line) => line.startsWith("  - ")).map((line) => line.slice(4));
  const wanted = pattern === null ? [] : [pattern];
  check(
    label,
    r.status === expected && named.join("\n") === wanted.join("\n"),
    `exit ${r.status}, wanted ${expected}; named ${JSON.stringify(named)}, wanted ${JSON.stringify(wanted)}`,
  );
}

// The footer that reached #169 fails on its own, and names the link and the
// footer both, which is what the author has to take out.
const r169 = run(pr169);
check(
  "BLOCK  the footer that reached #169",
  r169.status === 1 && r169.stderr.includes(LINK) && r169.stderr.includes(FOOTER),
  `exit ${r169.status}\n${r169.stderr}`,
);

const total = cases.length + 1;
console.log(failed === 0 ? `\nall ${total} cases pass` : `\n${failed} case(s) failed`);
process.exit(failed === 0 ? 0 : 1);
