#!/usr/bin/env python3
"""Regenerate the two power-of-five tables `runtime/runtime.c` uses for Ryu.

    python3 scripts/gen-pow5-tables.py

Prints the C to stdout; paste it over the `NISH_POW5_INV_SPLIT` and
`NISH_POW5_SPLIT` definitions. The point of having this in the tree is that
the ~10 KB of constants in the runtime are *derived*, with exact integer
arithmetic, rather than transcribed from somewhere -- so a reader can check
them rather than trust them. See docs/wp15-performance.md section 7a.

The code that reads the tables is adapted from Ryu (ryu/d2s.c and
ryu/common.h, Copyright 2018 Ulf Adams) under the Boost Software License,
Version 1.0; runtime/LICENSE-ryu has the text and THIRD_PARTY_NOTICES.md the
entry.
"""
INV_BITCOUNT = 125
BITCOUNT = 125
M = (1 << 64) - 1

def pow5bits(i):
    return (5 ** i).bit_length()

inv = []
for i in range(292):
    p = 5 ** i
    j = p.bit_length() - 1 + INV_BITCOUNT
    v = (1 << j) // p + 1
    assert v >> 128 == 0, i
    inv.append((v & M, v >> 64))

spl = []
for i in range(326):
    p = 5 ** i
    j = p.bit_length() - BITCOUNT
    v = p << -j if j < 0 else p >> j
    assert v >> 128 == 0, i
    spl.append((v & M, v >> 64))

def emit(name, rows):
    out = [f"static const uint64_t {name}[{len(rows)}][2] = {{"]
    for lo, hi in rows:
        out.append(f"  {{ {lo}u, {hi}u }},")
    out.append("};")
    return "\n".join(out)

print("/* Generated by scripts/gen-pow5-tables.py; do not hand-edit. */")
print(emit("NISH_POW5_INV_SPLIT", inv))
print()
print(emit("NISH_POW5_SPLIT", spl))
