/**
 * Stable diagnostic codes: the `code` field of every `--json` object.
 *
 * Kept by hand since R6: a new rule takes its band's next free code, which `node scripts/gen-diagnostic-codes.mjs`
 * prints, in longest-fragment-first order; its `--check` (run by `npm test`) validates bands, order and uniqueness.
 *
 * A code is a promise: NL2043 means the same rule next release as it does now.
 * `NL` is for Nish Lang -- the language is `Nish` everywhere a human reads it,
 * and `Nish Lang` is the longer form the project uses where a bare name would
 * be ambiguous, the way Rust writes `rust-lang`. The prefix is a literal here
 * rather than a value from `branding.ts`: a code is matched on by tooling that
 * has to keep working across a rename, so it is frozen by design.
 * So numbers are only ever *appended*, and a retired rule keeps its entry, and
 * its number reserved. The bands follow the pipeline: NL0001 a syntax error,
 * NL1xxx Phase 0, NL2xxx the checker, NL3xxx the driver, NL4xxx the interop
 * sidecars, NL7xxx a deprecation warning, NL8xxx a WP33 portability warning,
 * NL9xxx a WP15 section 8 performance warning, and NL0000 a diagnostic no rule
 * matched yet.
 *
 * Codes are carried in `--json` only. The human summary line
 * `file:line:col: error: <text>` is unchanged and stays byte-for-byte what it
 * has always been, because the `.err` goldens and `tests/self/reject-oracle.js`
 * match on it.
 *
 * A fragment is the longest literal run of a message's template -- the rule in
 * words, with the interpolated names, types and counts removed -- and is matched
 * as a substring, because many messages open with the thing they are about and
 * name the broken rule only afterwards. Cutting at the interpolations is also
 * why no fragment here spells the project's name: "... is forbidden in
 * ${LANGUAGE}" contributes the run before the name, leaving `branding.ts` the
 * only place it lives.
 */

/** No rule matched: the diagnostic has no code yet. */
const UNCODED: string = "NL0000"

/** Every syntax error shares one code: stage0 takes that text from the `typescript` package. */
const SYNTAX: string = "NL0001"

/**
 * Band 0 is what is wrong with the *run* rather than with the program: the C
 * toolchain `--link` needs could not be used (exit 3), and an internal compiler
 * error (exit 70). Neither has a source location.
 */
export const TOOLCHAIN: string = "NL0002"
export const INTERNAL: string = "NL0003"

/**
 * @public Number of rules that carry a code. Nothing in the compiler reads it;
 * `scripts/gen-diagnostic-codes.mjs --check` holds it to the tables' length.
 */
export const RULE_COUNT: i32 = 599

/**
 * Fragment, code, fragment, code -- flat because the language has no tuple, and
 * a function rather than a module constant because a constant's initialiser
 * must be a literal (`src/target.ts` holds its table the same way). The
 * function is an arrow bound to a `const`, which is how `src/` declares one
 * since WP22 stage C; a concise body is exactly what a table-returning function
 * wants. Longest fragment first, so a specific rule wins over a general one it
 * contains.
 */
const diagnosticRules = (): string[] => [
  "`using` takes only `scope()` or a `Mutex`'s `lock()` from `nish/threads`, or the builtin `arena()`, in this version: they are the values whose disposal the language defines — a scope joins its tasks, a guard releases its lock, an arena releases what its block allocated — so a `using` of anything else would promise a disposal nothing performs",
  "NL2387",
  ": a scope's tasks run, and store their answers, when its block ends, and under Node each runs and stores where it is spawned, so a destination is a fresh `const` array that is never handed on, and between a scope's first `spawn` and the end of its block its thread neither reads a destination nor writes memory a task may read",
  "NL2394",
  "The task given to `spawn` must be a top-level function named at the call, not an arrow: a task is a unit of work a thread runs on its own, and its name is what a debugger or a profiler shows for that thread (declare the arrow as a `const` of the module and pass its name)",
  "NL2391",
  "` cannot declare `[Symbol.dispose]`: in this version `using` takes only a `scope()` or a `lock()` from `nish/threads` or the builtin `arena()`, whose join and releases the compiler emits itself, so a disposal method of any other class would never be called",
  "NL2393",
  "` is a `Secret`, and a `Secret` is not copied: two names for one key would leave one of them to be wiped by nobody. Pass it to a function, return it, `wipe` it, or move a local the function made into another (`const j = k`), after which `k` is not read",
  "NL2444",
  ": inside a guard's block, directly or through any function it calls, there is no second `lock()`, no `scope()` or `spawn`, and no `parallelMapInto` or `parallelReduce`, so one lock is held at a time and nothing is waited on while it is held",
  "NL2470",
  "`, which is no module of this program: an entry is the path of a module the program compiles, relative to the `package.json` that lists it, and one that names nothing would leave the module it meant outside the scope without a word",
  "NL3031",
  "`arena()` must be the initialiser of a `using` declaration, `using a = arena()`: the arena releases what was allocated after it when the block that declares it ends, and an `arena()` written anywhere else has no block to end",
  "NL2416",
  "`new Mutex` takes a fresh value — a `new` expression or a literal — because the data a `Mutex` owns is reachable only through its guard, and a value the program already holds would be a path to it that skips the lock",
  "NL2463",
  "`: a key is hashed and compared by value, or by identity for a class instance, so it is a string, a number of any width, a boolean, an enum or a class, and not an interface, an array, a nullable type or a `Result`",
  "NL2353",
  "` is not supported: a constraint cannot mention a type parameter, because it is resolved once for the template rather than once per instantiation; name a class or interface, with any type arguments written out",
  "NL2326",
  "` through a guard, which stores only a number, a `boolean` or an enum, into a field or an element that already exists: a task's arena is freed when it is joined, and a pointer into it stored here would dangle",
  "NL2468",
  ": a foreign pointer may only appear in a `declare function` signature or on a local bound to one, because it is an address a C function owns and this compiler can neither lay it out nor say how long it lives",
  "NL2323",
  "`, before the scope joins: natively the scope's tasks run when its block ends and under Node each runs where it is spawned, so the parent locks what they share only before the first `spawn` or after the join",
  "NL2472",
  "` cannot hold a `Secret`: an element, a `Result` payload or a type argument outlives the function that made the secret, which then can neither return nor wipe it; hold a `Secret` in a local or a parameter",
  "NL2429",
  " and cannot be the operand of an operator other than `??`, `=== undefined` and `!== undefined`: give it a default with `??` first, or bind it to a `const` and use it where `!== undefined` has narrowed it",
  "NL2367",
  "` is called through a guard, which reads and stores fields and elements and calls no method: a method could keep what it reaches, or grow an array into a task's arena, which is freed when it is joined",
  "NL2469",
  "A `Secret` can be compared only with another `Secret` or with `null`: comparing it with a value would answer a question about the key, in time that depends on it. Use `timingSafeEqual` inside `expose`",
  "NL2433",
  "`lock()` must be the initialiser of a `using` declaration, `using g = m.lock()`: the lock is released when the block that declares it ends, so a guard bound any other way would be one nobody releases",
  "NL2465",
  "` runs it on several threads that each have an arena of their own: a parallel body may not call `Arena.mark`, `Arena.used`, `Arena.release` or `Arena.reset`, nor open a `using a = arena()` block",
  "NL2351",
  "`, which belongs to the function it is written in: an arrow argument is lifted into a function of its own and sees only its parameters and the module's top-level names, so it can capture nothing",
  "NL2335",
  "; a constructor or method is named after its class, so two classes that share a name anywhere in the program cannot both declare it, whether or not either is exported; rename one of the classes",
  "NL3022",
  " and cannot be stored in an array element: a value that may be missing is never in memory; store a default with `??`, or bind it to a `const` and store it where `!== undefined` has narrowed it",
  "NL2365",
  " and cannot be passed as an argument: a value that may be missing does not cross a call; give it a default with `??`, or bind it to a `const` and pass it where `!== undefined` has narrowed it",
  "NL2362",
  " and is stored into memory — handed to a callee that keeps it, or held by an object or an array — where this analysis stops following it, so nothing proves it is gone when the block releases",
  "NL2421",
  ", and the array is older than the block: a `push` moves the array's storage into the arena, which the block releases when it ends (push only onto a `const` the block binds to a fresh array)",
  "NL2422",
  ">` is not key material: a `Secret` holds an array of integers (`u8[]`, `u32[]`, ...) or a record whose every field is an integer, because `wipe` has to reach every byte of it with one store",
  "NL2428",
  "; a constructor or method is named after its class, so two classes that share a name within one package cannot both declare it, whether or not either is exported; rename one of the classes",
  "NL3023",
  "` cannot have a function type here: a function type may only annotate a parameter of a top-level function, which is monomorphised for each function it is given, and this is a parameter of ",
  "NL2338",
  "` read through a guard, which is used only as the base of a field or element read or store: a value that is not a number, a `boolean` or an enum would outlive the block that holds the lock",
  "NL2467",
  "` releases what a body allocates after every element: a parallel body may allocate only temporaries it drops before it returns, and this analysis stops following a value once it is stored",
  "NL2352",
  " and cannot initialise a `const` annotated with its value type: annotate the `const` with the whole type, or with none, and test it with `!== undefined`, or give it a default with `??`",
  "NL2368",
  "` cannot be a `Secret`: a field of a class or interface outlives the function that made the secret, which then can neither return nor wipe it; hold a `Secret` in a local or a parameter",
  "NL2430",
  " and cannot be stored in a field: a value that may be missing is never in memory; store a default with `??`, or bind it to a `const` and store it where `!== undefined` has narrowed it",
  "NL2364",
  "` is the binding of a `using` declaration of `arena()` and cannot be read: it holds the mark its block releases to when it ends, and nothing but that release may see or move the mark",
  "NL2417",
  "`secret` takes a value only it will hold: a fresh value (a call, `new`, a literal) or a local it moves, not a parameter, a field or an element, whose owner would keep the plain bytes",
  "NL2447",
  " and cannot be returned: a value that may be missing does not cross a call; return a default with `??`, or bind it to a `const` and return it where `!== undefined` has narrowed it",
  "NL2363",
  " and cannot be held in a `let`: only a `const` is narrowed, because a `let` can be assigned; bind it with `const` and test it with `!== undefined`, or give it a default with `??`",
  "NL2361",
  "`scope()` must be the initialiser of a `using` declaration: a scope joins its tasks when the block that declares it ends, so a scope bound any other way would be one nobody joins",
  "NL2388",
  " and cannot be a template literal hole: there is no `undefined` to print; give it a default with `??`, or bind it to a `const` and print it where `!== undefined` has narrowed it",
  "NL2366",
  ", outside the no-panic scope this call is in, where nothing the caller proves can remove it: call a function that cannot panic, or make the call from a module outside the scope",
  "NL2458",
  "` is not a member a program may name: the data a `Mutex` owns is reachable only through the guard its `lock()` answers, `using g = m.lock()`, so every path to it takes the lock",
  "NL2464",
  "`: the block releases what it allocated when it ends, and nothing proves the object it is stored into ends with it (allocate what must outlive the block before the block opens)",
  "NL2419",
  "` is made here and nobody owns it: a `Secret` leaves the function that made it returned or wiped, so bind it to a local (`const s = ...`) and `wipe(s)` once done, or return it",
  "NL2439",
  "`: the block releases what it allocated when it ends, and nothing proves the array it is stored into ends with it (allocate what must outlive the block before the block opens)",
  "NL2420",
  "An arrow may only be written as the argument for a function-typed parameter of a top-level function, which lifts it into a function of its own: a function is never a value in ",
  "NL2336",
  "` (supported: number, i32, i64, u8, u16, u32, u64, f32, f64, boolean, string, void, T[], Result<T, E>, Int32Array/Float64Array/BigInt64Array, and declared classes/interfaces)",
  "NL2039",
  "; a function name must be unique within its own package whether or not it is exported, because the whole-program attribute analysis is keyed by the package-scoped symbol",
  "NL3027",
  "`, which could be the array `parallelMapInto` is writing: another thread would be writing it while this one reads, so `dst` may not be reachable from an element of `src`",
  "NL2347",
  "`: a `Mutex` reaches a task as its argument or as a field of the class its argument is, never deeper, so which tasks share a lock is a question the checker can answer",
  "NL2473",
  "A `Secret` cannot be interpolated into a template literal: what it holds would leave in the string. Compute with it inside `expose` and interpolate what that returns",
  "NL2431",
  ".value` only as the base of a field or element read or store: passed, bound, stored, returned or walked, what it reaches would outlive the block that holds the lock",
  "NL2466",
  "`, which is not associative: `parallelReduce` folds each block from the identity and then combines the blocks, which is a left fold only for an associative operator",
  "NL2349",
  " and cannot be the default of another `??`: the default stands in for a missing value, so it is a value; give this one a default of its own first, `a ?? (b ?? d)`",
  "NL2371",
  "` cannot be nullable: a foreign pointer is narrowed with `!== null` before it is passed back, because only the C function it came from can hand out a null one",
  "NL2324",
  ", and that scope is declared outside the block: the task runs, and its answer is stored, when the scope joins, after the block has released what it allocated",
  "NL2427",
  " cannot be passed as an argument: an iterator is not a value in this version, so pass the `Map` or `Set` itself and walk it in the callee with a `for...of`",
  "NL2373",
  "` runs may reach no I/O, no clock, no entropy, no C, and no `panic` or exit whose message or status is computed, so that what it returns is all that leaves",
  "NL2448",
  "` hands it — returns it, stores it or passes it where it is kept — and the key would outlive the `Secret` unwiped; return a value computed from it instead",
  "NL2449",
  "` that can reach the end of its block neither wiped nor returned: a `Secret` leaves the function that made it returned or wiped, on every path, so `wipe(",
  "NL2441",
  "; a function name must be unique across the program whether or not it is exported, because the whole-program attribute analysis is keyed by symbol name",
  "NL3026",
  "`: a value is stored in the table as it is, so it may not be `void`, nor an interface, whose record would be copied in rather than shared (use a class)",
  "NL2354",
  "` function and is called only through an import of it, so that each module that gives up a check or defines a wrap says so at its top: add `import { ",
  "NL2456",
  "A `Secret` cannot be indexed or be an index: either reads key material outside `expose`, and an index that depends on a key is a cache-timing channel",
  "NL2435",
  "`, which is declared outside the block: the block releases what it allocated when it ends, and the local would outlive it pointing into freed memory",
  "NL2418",
  " cannot be returned: an iterator is not a value in this version, so return the `Map` or `Set` itself and walk it with a `for...of` where it is used",
  "NL2374",
  "` hands back only a number, a `boolean` or an enum: a worker's arena is freed when its thread exits, so anything else would point into freed memory",
  "NL2348",
  "; a class or interface name must be unique across the program whether or not it is exported, because a struct type is identified by its name alone",
  "NL3028",
  "A `using` declaration must be a statement of a block, `{ ... }`: its scope joins when that block ends, and a single-statement body is not a block",
  "NL2390",
  "`, whose `[key, value]` pairs need destructuring, which this version does not have: walk `keys()` or `values()` instead, as in `for (const k of ",
  "NL2375",
  ", and `spawn` runs it beside the scope's other tasks: a task may write shared memory only through the guard of a `Mutex`, `using g = m.lock()`",
  "NL2471",
  "` can only be the receiver of a `spawn` statement: passed, stored, returned or copied, it could be given a task after its block has joined it",
  "NL2389",
  "` that this exit leaves neither wiped nor returned: a `Secret` leaves the function that made it returned or wiped, on every path, so `wipe(",
  "NL2440",
  "` runs it on threads whose arenas are freed when they exit: a parallel body may not allocate (a string, an array, an object or a `Result`)",
  "NL2346",
  " cannot be stored: an iterator is not a value in this version, so a `Map` or `Set` is walked where it is, as the iterable of a `for...of`",
  "NL2372",
  " (it aborts rather than unwinding): return a `Result<T, E>` for a failure a caller should handle, or `panic(message)` to end the process",
  "NL1001",
  " and stores an allocation into memory, where this analysis stops following it: what it stores may be the block's and outlive the release",
  "NL2424",
  "` runs it on several threads at once: a lock is taken by a scope's task or by the thread that opened the scope, never by a parallel body",
  "NL2474",
  "`: a `Map` or `Set` in this version has no `entries` or `forEach`, because there is no destructuring and a method cannot take a function",
  "NL2356",
  "` is not supported: a constraint must be a declared class or interface, because the members a type parameter has are its constraint's",
  "NL2327",
  "` writes the argument `exposeWith` hands it, a channel out of `expose` its result type does not name: return what it computes instead",
  "NL2450",
  "` cannot be handed a `Secret`: a builtin reaches the outside world or reads the bytes, and a `Secret` is read only through `expose`",
  "NL2432",
  "A `Secret` cannot be a condition: a branch taken on key material is a timing channel, and a `Secret` is read only through `expose`",
  "NL2434",
  " can only be the iterable of a `for...of`, which walks the entries in insertion order: an iterator is not a value in this version",
  "NL2358",
  ", and this analysis cannot see what it does with memory, so nothing proves that what the block allocated is gone when it releases",
  "NL2425",
  "`, which a task cannot be handed: a `Result` is passed as its parts rather than as one value, so hand the task the value it holds",
  "NL2392",
  ": the block releases to the mark it took when it opened, which a release or a reset in between has already moved the arena below",
  "NL2426",
  "(...)` needs a contextual `Result<T, E>` type (annotate the function's return type, e.g. `function f(): Result<number, string>`)",
  "NL2035",
  "` may panic here, and a module in the no-panic scope (`--deny-panics` or `noPanic`) may keep no panic site but out of memory: ",
  "NL2457",
  "` is assigned again while the `Secret` it holds is neither wiped nor returned, and that secret would be lost unwiped: `wipe(",
  "NL2442",
  "` of a `Secret` is read only by `nish:secret` itself: compute with the value inside `expose(key, f)`, which runs `f` with it",
  "NL2436",
  "` was moved into another `Secret` local and cannot be read again: one key has one owner, which is the one that wipes it",
  "NL2446",
  " | null` is not supported: only class, interface, array, and string types can be nullable (a scalar has no null value)",
  "NL2010",
  ", which can only initialise a `const`, be the left operand of `??`, or be compared with `undefined` by `===` or `!==`",
  "NL2369",
  "` is a function parameter and can only be called or passed on as a function argument: a function is never a value in ",
  "NL2334",
  "`case` label must be an integer literal, a module constant, or an enum member (LLVM's `switch` table holds constants)",
  "NL2284",
  "` runs it on several threads at once: a parallel body may read what its caller owns and write nothing but its result",
  "NL2345",
  "Type aliases cannot be exported: an alias names a type inside one module (declare it in every module that needs it)",
  "NL2276",
  "` is a function type, which may only annotate a parameter of a top-level function: a function is never a value in ",
  "NL2337",
  "finding, because the arena memory it describes stays allocated after nothing in the program can reach it any more",
  "NL2462",
  "`const enum` is not supported: an enum member is already folded to its integer, so `const` would ask for nothing",
  "NL2285",
  "; a class or interface name must be unique across the program, and an instantiation is named after its template",
  "NL3013",
  ": the block releases what it allocated before the function returns, so the caller would be handed freed memory",
  "NL2423",
  "` is refused: Nish has no `Date` object; the one `Date` member is `Date.now()`, the wall clock in milliseconds",
  "NL2401",
  "`main` cannot be generic: the entry point is called by the C runtime, which has no type arguments to give it",
  "NL2300",
  "`super(...)` is only valid as the first statement of the constructor of a class that `extends` another class",
  "NL2155",
  "` exceeds 2^53 and cannot be written exactly (the parser already rounded it); compute the i64 value instead",
  "NL2055",
  "Enums cannot be exported: an enum names a type inside one module (declare it in every module that needs it)",
  "NL2288",
  ".capabilities` is an object with an `allow` list, a `deny` list or both, each an array of capability names",
  "NL3032",
  "` may have been wiped already, and a wiped `Secret` holds zeros: read it before `wipe`, or make a new one",
  "NL2443",
  "Object literal needs a contextual class or interface type (annotate the variable: `const p: P = { ... }`)",
  "NL2224",
  "Parameter properties (`constructor(public x: number)`) are not supported; declare the field and assign it",
  "NL2234",
  "`extends` is not supported: Nish has no inheritance. Declare the base's fields as the first fields of `",
  "NL2278",
  "A `case` clause cannot declare a variable directly; wrap the clause body in a block (`case 1: { ... }`)",
  "NL2165",
  "`: a `Map` has size, get, set, has, delete and clear, and a `Set` has size, add, has, delete and clear",
  "NL2359",
  "; a function name must be unique across the program, and an instantiation is named after its template",
  "NL3010",
  "` copies bytes, so it needs an array whose elements are numbers (`u8[]`, `i32[]`, `f64[]`, ...), got ",
  "NL2395",
  "`export { ... }` / `export * from` are not supported; put `export` on the function declaration itself",
  "NL2128",
  "` is both allowed and denied in the root package's capability policy; a policy says one or the other",
  "NL3035",
  "`case` label must be an integer literal or a module constant (LLVM's `switch` table holds constants)",
  "NL2123",
  "` field is one object, written once, whose keys are `noPanic` and `capabilities`, each written once",
  "NL3036",
  " compiles one copy of a package per program, so every import of it has to reach the same directory",
  "NL3029",
  "; if (r.isErr()) { ... }`), propagate it with `.orReturn()`, or end on it with `.expect(message)`",
  "NL2025",
  "`super` can only be used as `super.method(...)`, or as `super(...)` at the start of a constructor",
  "NL2157",
  "` is read-only: it counts the entries, and `set`, `add`, `delete` and `clear` are what change it",
  "NL2360",
  "` returns must be a declared type that holds no `Secret`: that type is the one thing that leaves",
  "NL2451",
  "`, and the push may move that storage first; copy the fields you need into locals before pushing",
  "NL2291",
  "`, which is not a range this compiler reads: the one it accepts is a floor, `>=X.Y.Z` or `>=X.Y`",
  "NL3019",
  "`null` needs a contextual `T | null` type (annotate the variable, e.g. `let p: P | null = null`)",
  "NL2145",
  ")` and cannot be read again: the plain array would be key material outside the `Secret`'s rules",
  "NL2445",
  "`; a class or interface name is program-wide, so one program cannot have both (rename this one)",
  "NL3030",
  "`declare function` cannot be generic: a C symbol is one function, not a template to instantiate",
  "NL2307",
  "`Result<T, E> | null` is not supported: a `Result` already models absence through its error arm",
  "NL2151",
  ">(n)` would zero-fill with 0, which is outside the range; build it with `[]` and `push` instead",
  "NL2386",
  "` is no capability: a policy names capabilities as `--emit-capabilities` reports them, one of ",
  "NL3033",
  "` returns is the one thing that leaves the secret, so it is written down rather than inferred",
  "NL2452",
  "A `case` clause with statements must end in `break`, `return`, `continue` or `process.exit` (",
  "NL2166",
  "`super` is only valid inside a method or constructor of a class that `extends` another class",
  "NL2159",
  "A module constant's initialiser must be a literal, another constant, or arithmetic over them",
  "NL2167",
  " (it enumerates property names, and object layout is fixed at compile time); use `for...of`",
  "NL1056",
  "` allocates a dynamically sized array on every iteration of this loop and nothing keeps it ",
  "NL2042",
  "`, because that entry declares none of the conditions this compiler compiles source from (`",
  "NL3020",
  "; a class or interface name is still program-wide, so two packages cannot both declare one",
  "NL3009",
  "` exceeds 2^53 and cannot be written exactly (the parser already rounded it); compute the ",
  "NL2054",
  "` is rebuilt from its own value on every iteration of this loop, so every pass copies all ",
  "NL2087",
  "` (Phase 1 supports number, i32, i64, u8, u16, u32, u64, f32, f64, boolean, string, void)",
  "NL2038",
  "` is not supported yet: its result is `V | undefined`, and this version cannot narrow one",
  "NL2357",
  "`process.argv` requires a `main` entry point (this program has no `export function main`)",
  "NL2149",
  "`Result<T, void>` is not supported: an error must carry a value (use `Result<T, string>`)",
  "NL2152",
  "` takes no arguments in this version: a `Map` or `Set` starts empty, so create it with `",
  "NL2355",
  "`integer` is reserved for ranged integers (`integer<Lo, Hi>`) and cannot be declared as ",
  "NL2332",
  "`integer<Lo, Hi>` is reserved for ranged integers, which this compiler does not have yet",
  "NL2333",
  "`super` is not supported: Nish has no inheritance, so a class has no base class to reach",
  "NL2279",
  "` is not a module constant, and a module constant's value must be known at compile time",
  "NL2080",
  "`: a class's type parameters are in scope in its methods, and a diagnostic that names `",
  "NL2331",
  "Only functions can be exported for now, plus classes and interfaces (found `export` on ",
  "NL2226",
  "` must be relative (`./x`, `../x`), a package name (`hash`, `@scope/hash`), or one of ",
  "NL2320",
  "` must be the name of a top-level function or an arrow written at the call, because `",
  "NL2339",
  "` specifier names a module inside it, so no segment may be empty or begin with a `.`",
  "NL3016",
  "` under a type constructor instead of passing it on, so the chain has no end; name `",
  "NL2319",
  "` under a type constructor instead of passing it on, so the chain has no end; pass `",
  "NL2309",
  "`declare function` declares a C function this program calls, so it must have no body",
  "NL2308",
  " (an export is a declaration, and a declaration has a name; import it by that name)",
  "NL1058",
  ": a `Result` is immutable once built (return a new `ok(...)` or `err(...)` instead)",
  "NL2028",
  ": a `Result` is immutable once built (return a new `Ok(...)` or `Err(...)` instead)",
  "NL2270",
  " (an import names source this compiler reads, never a resource loaded at run time)",
  "NL1057",
  " is not well-formed JSON, so this compiler could not read an entry point out of it",
  "NL3021",
  "`; check the nullable side against `null` first, then compare the narrowed values",
  "NL2114",
  ": --emit-napi-async requires --threads (its exports allocate on a worker thread)",
  "NL3012",
  "` is not supported; a module has no top-level code, so only `const` is available",
  "NL2084",
  "Operator `+` requires two operands of the same numeric type or two strings, got ",
  "NL2231",
  "` cannot be exported: it is a C function this program calls, not one it defines",
  "NL2306",
  "`export default` / `export =` are not supported; use a named `export function`",
  "NL2129",
  "`ReadonlyArray` needs exactly one type argument, e.g. `ReadonlyArray<number>`",
  "NL2266",
  "` in C, so a header that declared both would not compile: rename one of them",
  "NL4008",
  "`: a constrained type parameter has only the members its constraint declares",
  "NL2330",
  "`main` cannot take parameters (command-line arguments are not supported yet)",
  "NL2139",
  "` mentions a type parameter no other argument binds; annotate the parameter",
  "NL2342",
  "` takes an array of numbers (i32, i64, u8, u16, u32, u64, f32 or f64), got ",
  "NL2455",
  "`for...of` needs a `const` or `let` declaration, e.g. `for (const x of xs)`",
  "NL2135",
  "`parallelReduce` folds every block from its identity, and the identity of `",
  "NL2350",
  "attempt to compute with overflow in a constant: the result does not fit in ",
  "NL2175",
  "Empty array literal needs a type annotation, e.g. `const xs: number[] = []`",
  "NL2199",
  "` is inspected, and the value it replaces is dropped: test it first with `",
  "NL2377",
  "`, which only its body could bind, and a block body's type is not inferred",
  "NL2343",
  "` of `integer<Lo, Hi>` is outside i32 (a ranged integer is always an i32)",
  "NL2382",
  "`set` copies from an array of the receiver's element type, so it expects ",
  "NL2396",
  ": `static` members are not supported (use a top-level function or const)",
  "NL2027",
  ": initializers must be literals (assign other values in the constructor)",
  "NL2030",
  "` is refused: the one `crypto` member is `crypto.getRandomValues(bytes)`",
  "NL2403",
  "`new Array` needs exactly one type argument, e.g. `new Array<number>(n)`",
  "NL2142",
  "`Result` needs exactly two type arguments, e.g. `Result<number, string>`",
  "NL2150",
  "A `Secret` is made by `secret(v)`, which moves `v` into it, not by `new`",
  "NL2437",
  "The right operand of `??` stands in for a missing value, so it must be `",
  "NL2370",
  " entry point: its `exports` gave this compiler no file to compile for `",
  "NL3014",
  "` values; compare each with `null` and then compare the narrowed values",
  "NL2108",
  "`: import `Secret`, `secret`, `expose`, `exposeWith` and `wipe` from `",
  "NL2453",
  "`main` must return void or an i32 number (the process exit code), not ",
  "NL2140",
  "Only relative import specifiers are supported (`./x` or `../x`), got `",
  "NL2227",
  "; exported names must be unique within the package that declares them",
  "NL3025",
  ".isErr()`, or use `.orReturn()`, `.unwrapOr(v)` or `.expect(message)`",
  "NL2032",
  ">` is an empty range: the lower bound is greater than the upper bound",
  "NL2381",
  "Only top-level function declarations are supported in Phase 1 (found ",
  "NL2230",
  "The `for...of` variable takes the element type; remove the annotation",
  "NL2242",
  " (the interface's fields must be the class's first fields, in order)",
  "NL2277",
  "` reaches the operating system, and a wasm32 build has none to reach",
  "NL2404",
  "Interface inheritance (`extends`) is not supported; list every field",
  "NL2215",
  " (use `if` / `else`; only an integer switch lowers to a jump table)",
  "NL2009",
  "` expects a number (i32, i64, u8, u16, u32, u64, f32, or f64), got ",
  "NL2057",
  "` is not supported: inherited fields are read and written as `this.",
  "NL2085",
  " only where it is instantiated, and this program instantiates none",
  "NL4007",
  ", and a range is a promise the C side never made: declare it `i32`",
  "NL2385",
  "`wipe` zeroes a `Secret`, or an array or record of integers, and `",
  "NL2438",
  "Function names starting with `nish_` are reserved for the runtime",
  "NL2202",
  " (a module has no runtime object; resolve paths at compile time)",
  "NL1060",
  "; convert the error first: `if (r.isErr()) { return Err(...); }`",
  "NL2023",
  "`; a derived class cannot redeclare or shadow an inherited field",
  "NL2112",
  "`: `static` members are not supported (use a top-level function)",
  "NL2116",
  "`export default` is not supported; use a named `export function`",
  "NL2130",
  "`super(...)` must be the first statement of the constructor of `",
  "NL2156",
  " (a module has no top-level code, so there is nothing to defer)",
  "NL1059",
  ", not in your program. Please report it with the input file and",
  "NL3002",
  "` is generic: it must be written with its type arguments, e.g. ",
  "NL2317",
  "` takes i32 or i64 operands (convert with toI32 or toI64), got ",
  "NL2454",
  "` takes u32 or u64 operands (convert with toU32 or toU64), got ",
  "NL2399",
  "`new Array<T>(n)` expects exactly 1 argument (the length), got ",
  "NL2143",
  " (it has `isOk`, `isErr`, `orReturn`, `unwrapOr` and `expect`)",
  "NL2005",
  "` is generic, so it names no one function to pass as argument ",
  "NL2341",
  "` takes its signature from the arrow; drop the annotation on `",
  "NL2273",
  "A bound of `integer<Lo, Hi>` must be an integer literal, got `",
  "NL2379",
  "Template literal hole must be string, number, or boolean, got ",
  "NL2238",
  "` is a built-in type name and cannot be used for a type alias",
  "NL2275",
  "`; a function argument must have exactly its parameter's type",
  "NL2340",
  "`Array` needs exactly one type argument, e.g. `Array<number>`",
  "NL2121",
  "`extends` must name exactly one class declared in this module",
  "NL2132",
  "` again afterwards rather than holding the element across it",
  "NL2290",
  "` cannot be used before `super(...)` in the constructor of `",
  "NL2047",
  "` expects 0 argument(s) (the class has no constructor), got ",
  "NL2056",
  "` in a constant requires two operands of the same type, got ",
  "NL2070",
  "`unwrapOr(...)` needs a success value to fall back to, and `",
  "NL2164",
  " (an override keeps the signature; there is no overloading)",
  "NL2001",
  ", and a declared C function returns a scalar or `CPtr` only",
  "NL2321",
  "` cannot declare methods (interfaces describe layout only)",
  "NL2048",
  "`integer` needs exactly two bounds, e.g. `integer<0, 255>`",
  "NL2378",
  ", and a declared C function takes scalars and `CPtr` only",
  "NL2322",
  "the command line at https://github.com/amritk/nish/issues",
  "NL3007",
  " generic instantiations, which is this compiler's limit ",
  "NL2295",
  ": definite-assignment assertions (`!`) are not supported",
  "NL2029",
  "` is a built-in type name and cannot be used for an enum",
  "NL2281",
  "`: a type parameter is inferred from the arguments, and ",
  "NL2299",
  "`this` cannot be used as a value in the constructor of `",
  "NL2161",
  "Array literal elements must all have the same type, got ",
  "NL2172",
  "Names starting with `nish_` are reserved for the runtime",
  "NL2220",
  "Only the entry module may declare `export function main`",
  "NL2229",
  " = ...`) is not supported: a type argument is inferred ",
  "NL2292",
  "` is a generic function, and a generic function cannot ",
  "NL2298",
  "` is read before it is assigned in the constructor of `",
  "NL2086",
  "`export default` is not supported; use a named `export`",
  "NL2131",
  " extends ...`) is not supported yet: an unconstrained ",
  "NL2294",
  " produces no value and can only be used as a statement",
  "NL2020",
  "` here: it only holds an error where the call failed; ",
  "NL2067",
  "` requires two operands of the same integer type, got ",
  "NL2101",
  "` requires two operands of the same numeric type, got ",
  "NL2102",
  '"`) are not supported; modules have no top-level code',
  "NL2033",
  "Generic type parameters are forbidden on a method in ",
  "NL1055",
  "` must start with `super(...)`: the constructor of `",
  "NL2094",
  "; there is no top-level code to build anything else",
  "NL2026",
  "); handle it here instead: `if (r.isErr()) { ... }`",
  "NL2037",
  "` (the base's constructor and methods are part of `",
  "NL2040",
  "` in a constant of integer type (annotate it `f64`)",
  "NL2068",
  "` is the opt-in to it, so a policy can only deny it",
  "NL3034",
  "`: an unconstrained type parameter has no members; ",
  "NL2329",
  "`Number` expects a string, number, or boolean, got ",
  "NL2146",
  "`readonly` is only permitted on an array type, got ",
  "NL2265",
  "`this` is only valid inside a method or constructor",
  "NL2162",
  "Union types other than `T | null` are forbidden in ",
  "NL1053",
  " cannot be optional (every field has a fixed slot)",
  "NL2015",
  "; exported names must be unique across the program",
  "NL3024",
  "` has no initializer and no constructor assigns it",
  "NL2066",
  "` returns void and can only be used as a statement",
  "NL2105",
  "`; check for null first: `if (a !== null) { ... }`",
  "NL2113",
  "Only direct calls to named functions are supported",
  "NL2225",
  "The `for...of` variable cannot have an initializer",
  "NL2241",
  " modules listed below. Link the .ll module(s) and",
  "NL4002",
  ", and a declared C function returns a scalar only",
  "NL2304",
  "` has no `value`: its success arm carries nothing",
  "NL2064",
  "` is only allowed as a bound of `integer<Lo, Hi>`",
  "NL2383",
  "`namespace` and `module` blocks are forbidden in ",
  "NL1027",
  "Default imports are not supported; use `import { ",
  "NL2190",
  "Index signatures are not supported in interface `",
  "NL2214",
  "Type arguments are not written at a call site in ",
  "NL2303",
  "` where a bound of `integer<Lo, Hi>` is expected",
  "NL2380",
  "Getters and setters are not supported in class `",
  "NL2209",
  " (build the parts with template literals first)",
  "NL2003",
  "` is not definitely assigned in the constructor",
  "NL2082",
  "` is not part of the standard library (it has: ",
  "NL3011",
  "`, which the capability policy does not grant (",
  "NL2459",
  " values; build it with `[]` and `push` instead",
  "NL2022",
  ", and a declared C function takes scalars only",
  "NL2305",
  "` has more than one constructor (no overloads)",
  "NL2063",
  "` is a builtin function and can only be called",
  "NL2312",
  "` requires two operands of the same type, got ",
  "NL2103",
  "`) are not supported; import functions by name",
  "NL2119",
  "Operator `~` requires an integer operand, got ",
  "NL2232",
  "Ternary branches must have the same type, got ",
  "NL2240",
  "; use `obj.name` (no dynamic property lookup)",
  "NL1009",
  "` directory above the importing module has it",
  "NL3015",
  "` is already declared as a class or interface",
  "NL2074",
  "` takes no type argument (it is an alias of `",
  "NL2107",
  "attempt to divide with overflow in a constant",
  "NL2177",
  "Index signatures are not supported in class `",
  "NL2213",
  "Object literal keys must be plain identifiers",
  "NL2223",
  "Optional/default parameters are not supported",
  "NL2233",
  "Regular expression literals are forbidden in ",
  "NL1050",
  "` in i32 number mode (use --number-mode f64)",
  "NL2071",
  "Type assertion to `unknown` is forbidden in ",
  "NL1052",
  " functions (identical to --emit-header). */",
  "NL4001",
  "` must have a body (no overload signatures)",
  "NL2091",
  "` takes no type argument (it is `new Array<",
  "NL2106",
  "`implements` must name a declared interface",
  "NL2137",
  "`switch` has more than one `default` clause",
  "NL2160",
  "Element access requires a numeric index in ",
  "NL1042",
  "Generic type parameters are forbidden on a ",
  "NL1054",
  ": `$` separates a generic's name from its ",
  "NL2296",
  "` accepts string, number, or boolean, got ",
  "NL2041",
  "` needs an explicit return type annotation",
  "NL2096",
  "` takes no type arguments: only a generic ",
  "NL2325",
  "`Math.clz32` expects an i32 or a u32, got ",
  "NL2460",
  "`substring` expects 1 or 2 arguments, got ",
  "NL2153",
  "Loose equality is forbidden; use === / !==",
  "NL1047",
  " (no runtime metadata or class rewriting)",
  "NL1006",
  " (object layout is fixed at compile time)",
  "NL1007",
  "` in a constant requires boolean operands",
  "NL2069",
  "` is a builtin value and cannot be called",
  "NL2314",
  "An enum member name must be an identifier",
  "NL2287",
  "Computed property names are forbidden in ",
  "NL1041",
  "Constructors cannot declare a return type",
  "NL2189",
  "Destructured parameters are not supported",
  "NL2192",
  "Enum members must be numeric literals in ",
  "NL1043",
  "Generic type parameters are forbidden in ",
  "NL1045",
  "Holes in array literals are not supported",
  "NL2210",
  "Import must name the functions it imports",
  "NL2211",
  "Import specifier must be a string literal",
  "NL2212",
  "Spread in array literals is not supported",
  "NL2237",
  "Unary `+` is forbidden; it converts, and ",
  "NL2271",
  " (array length is read-only; use `push`)",
  "NL2002",
  "`for...of` declares exactly one variable",
  "NL2134",
  "`indexOf` expects 1 or 2 arguments, got ",
  "NL2461",
  "`try`/`catch`/`finally` is forbidden in ",
  "NL1033",
  "`var` is forbidden; use `let` or `const`",
  "NL1036",
  "Destructured constants are not supported",
  "NL2191",
  "Nullish coalescing `??` is forbidden in ",
  "NL1048",
  "Type assertion to `any` is forbidden in ",
  "NL1051",
  " (modules are resolved at compile time)",
  "NL1002",
  "` needs a newer compiler: its `engines.",
  "NL3018",
  "` needs every operand of one type, got ",
  "NL2400",
  "`declare function` is not supported yet",
  "NL2125",
  "`Function` constructor is forbidden in ",
  "NL1021",
  "attempt to divide by zero in a constant",
  "NL2176",
  "Optional chaining `?.` is forbidden in ",
  "NL1049",
  "Return type mismatch: function returns ",
  "NL2236",
  " (fields must match exactly, in order)",
  "NL2004",
  "`, whose length is fixed: declare it `",
  "NL2415",
  "`slice` expects 1 or 2 arguments, got ",
  "NL2289",
  "Cannot declare a variable of type void",
  "NL2183",
  "` must be declared `const`, not `let`",
  "NL2272",
  "`break` outside of a loop or `switch`",
  "NL2122",
  "`fill` expects 1 to 3 arguments, got ",
  "NL2398",
  "`join` expects 0 or 1 arguments, got ",
  "NL2138",
  "A function declaration binds one name",
  "NL2274",
  "Only simple variables can be assigned",
  "NL2228",
  " (use --number-mode f64 or toF64(x))",
  "NL2008",
  "` is already declared in this module",
  "NL2076",
  "` is set twice in the object literal",
  "NL2088",
  "`, and this program is compiling in ",
  "NL3017",
  "`.prototype` access is forbidden in ",
  "NL1012",
  "`): the type name is part of the ABI",
  "NL2120",
  "`set` expects 1 or 2 arguments, got ",
  "NL2397",
  "`super(...)` in the constructor of `",
  "NL2154",
  "`void` expressions are forbidden in ",
  "NL1037",
  "Labeled statements are forbidden in ",
  "NL1046",
  "Labelled `continue` is not supported",
  "NL2218",
  " (it has `ok`, `value` and `error`)",
  "NL2006",
  " (no dynamic property interception)",
  "NL1003",
  "; use `null` with a `T | null` type",
  "NL1008",
  "` is already declared as a function",
  "NL2075",
  "` requires a numeric variable, got ",
  "NL2098",
  "`__proto__` access is forbidden in ",
  "NL1010",
  "`; use an object literal: `{ ... }`",
  "NL2115",
  "`async` functions are forbidden in ",
  "NL1015",
  "`bigint` literals are forbidden in ",
  "NL1016",
  "Array length must be a number, got ",
  "NL2171",
  "Comma expressions are forbidden in ",
  "NL1040",
  "Generic functions are not supported",
  "NL2207",
  "internal: array method on non-array",
  "NL2216",
  "Type-only imports are not supported",
  "NL2243",
  "Unsupported expression in Phase 1: ",
  "NL2256",
  "Unsupported object literal member: ",
  "NL2258",
  "` expects exactly 1 argument, got ",
  "NL2061",
  "` must declare at least one member",
  "NL2283",
  "` must have plain identifier names",
  "NL2092",
  "`expect(...)` expects string, got ",
  "NL2127",
  "`for...of` requires an array, got ",
  "NL2136",
  "Abstract classes are not supported",
  "NL2168",
  "Array index must be a number, got ",
  "NL2170",
  "Unsupported statement in Phase 1: ",
  "NL2260",
  "Unsupported unary operator `-` on ",
  "NL2262",
  "Unsupported unary operator `!` on ",
  "NL2263",
  "` because it is a module constant",
  "NL2043",
  "` but not exported (add `export`)",
  "NL2045",
  "` requires boolean operands, got ",
  "NL2099",
  "`declare global` is forbidden in ",
  "NL1019",
  "`Math.abs` expects a number, got ",
  "NL2141",
  "async functions are not supported",
  "NL2173",
  "Cannot assign to readonly field `",
  "NL2181",
  "Generic classes are not supported",
  "NL2206",
  "Generic methods are not supported",
  "NL2208",
  "Labelled `break` is not supported",
  "NL2217",
  "Rest parameters are not supported",
  "NL2235",
  "Unsupported assignment operator `",
  "NL2253",
  "Unsupported interface member in `",
  "NL2257",
  "(...)` is a `Result<T, E>`, not ",
  "NL2034",
  "`, which does not extend a class",
  "NL2111",
  "`Function` type is forbidden in ",
  "NL1023",
  "`super` expects 0 argument(s) (`",
  "NL2158",
  "Expected a return value of type ",
  "NL2201",
  "` before the error is handled; ",
  "NL2044",
  "` is a constant imported from `",
  "NL2072",
  "` is a function imported from `",
  "NL2073",
  "` is defined in terms of itself",
  "NL2077",
  "` when checking a single module",
  "NL2109",
  "`declare enum` is not supported",
  "NL2286",
  "`new Function` is forbidden in ",
  "NL1028",
  "async methods are not supported",
  "NL2174",
  "Cannot assign to an element of ",
  "NL2267",
  "Condition must be boolean, got ",
  "NL2188",
  "Ternary branches cannot be void",
  "NL2239",
  "--target: unsupported target `",
  "NL3001",
  "` does not implement it; pass ",
  "NL2328",
  "` expects a number index, got ",
  "NL2058",
  "` expects an argument of type ",
  "NL2268",
  "` is a builtin imported from `",
  "NL2313",
  "` must return a value of type ",
  "NL2093",
  "`bigint` type is forbidden in ",
  "NL1017",
  "`in` operator is forbidden in ",
  "NL1025",
  "`symbol` type is forbidden in ",
  "NL1031",
  "`Symbol` type is forbidden in ",
  "NL1032",
  "Destructuring is not supported",
  "NL2193",
  "Object spread is forbidden in ",
  "NL1061",
  "` is not a declared interface",
  "NL2079",
  "`globalThis` is forbidden in ",
  "NL1024",
  "`instanceof` is forbidden in ",
  "NL1026",
  "Array elements cannot be void",
  "NL2169",
  "Cannot index a value of type ",
  "NL2184",
  "The arrow passed as argument ",
  "NL2344",
  "Unsupported binary operator `",
  "NL2254",
  "Unsupported class member in `",
  "NL2255",
  " (no event loop or promises)",
  "NL1004",
  " (no interpreter at runtime)",
  "NL1005",
  "` has no exported function `",
  "NL2376",
  "` is already imported from `",
  "NL2315",
  "` must be an integer literal",
  "NL2282",
  "`__proto__` is forbidden in ",
  "NL1011",
  "`arguments` is forbidden in ",
  "NL1014",
  "`continue` outside of a loop",
  "NL2124",
  "`for await` is not supported",
  "NL2133",
  "Generators are forbidden in ",
  "NL1044",
  "Generators are not supported",
  "NL2205",
  "Unsupported unary operator `",
  "NL2261",
  "()` in the constructor of `",
  "NL2036",
  "` (the builtin modules are ",
  "NL2310",
  "` cannot extend interface `",
  "NL2049",
  "` sends from a `u8[]`, got ",
  "NL2405",
  "`debugger` is forbidden in ",
  "NL1018",
  "`Function` is forbidden in ",
  "NL1022",
  "`new` requires a class name",
  "NL2144",
  "`process.argv` is read-only",
  "NL2148",
  "Cannot assign to property `",
  "NL2180",
  ": cannot create the result",
  "NL4003",
  "` expects a value of type ",
  "NL2269",
  "` is not generic, so `new ",
  "NL2318",
  "` is outside the range of ",
  "NL2384",
  "`, which already extends `",
  "NL2110",
  "`Reflect` is forbidden in ",
  "NL1029",
  "`unknown` is forbidden in ",
  "NL1035",
  "Duplicate declaration of `",
  "NL2195",
  "Duplicate type parameter `",
  "NL2302",
  "Functions must have a body",
  "NL2204",
  " but the discriminant is ",
  "NL2014",
  ": internal compiler error",
  "NL3003",
  "` needs a type annotation",
  "NL2095",
  "`: unsupported modifier `",
  "NL2118",
  "`delete` is forbidden in ",
  "NL1020",
  "`Symbol` is forbidden in ",
  "NL1030",
  "`typeof` is forbidden in ",
  "NL1034",
  " but its initializer is ",
  "NL2013",
  " needs a type annotation",
  "NL2019",
  ": unsupported modifier `",
  "NL2031",
  "` expects a string, got ",
  "NL2059",
  "` fills an `i32[]`, got ",
  "NL2406",
  "` has been instantiated ",
  "NL2297",
  "` returns before field `",
  "NL2104",
  "`unwrapOr(...)` expects ",
  "NL2163",
  "`yield` is forbidden in ",
  "NL1039",
  "Duplicate `case` label `",
  "NL2194",
  "; declare the type as `",
  "NL2024",
  "`with` is forbidden in ",
  "NL1038",
  "=1 for the stack trace)",
  "NL3005",
  "Functions must be named",
  "NL2203",
  "Unreachable code after ",
  "NL2251",
  " (the element type of ",
  "NL2007",
  " are not supported yet",
  "NL2293",
  " cannot have type void",
  "NL2016",
  " clashes with method `",
  "NL2017",
  "` cannot extend itself",
  "NL2050",
  "` clashes with field `",
  "NL2051",
  "` fills a `u8[]`, got ",
  "NL2402",
  "` is not available on ",
  "NL2081",
  "` needs an initialiser",
  "NL2097",
  "`any` is forbidden in ",
  "NL1013",
  "Cannot read property `",
  "NL2187",
  "could not be converted",
  "NL4005",
  "Unsupported operator `",
  "NL2259",
  " to write through it)",
  "NL2264",
  "` does not fit in i32",
  "NL2053",
  "` must be initialized",
  "NL2089",
  "Duplicate parameter `",
  "NL2198",
  "Non-integer literal `",
  "NL2222",
  "` cannot be optional",
  "NL2046",
  "` is missing field `",
  "NL2078",
  "Cannot find module `",
  "NL3006",
  "Duplicate function `",
  "NL2196",
  "Unknown identifier `",
  "NL2248",
  "` expects f64, got ",
  "NL2062",
  "`, which needs the ",
  "NL4004",
  "`Err(...)` expects ",
  "NL2126",
  "Negative literal `-",
  "NL2221",
  " are not supported",
  "NL2011",
  " argument(s), got ",
  "NL2012",
  " to an element of ",
  "NL2021",
  "` does not fit in ",
  "NL2052",
  "` expects exactly ",
  "NL2060",
  "` is not supported",
  "NL2083",
  "` must have a body",
  "NL2090",
  "`Ok(...)` expects ",
  "NL2147",
  "Cannot assign to `",
  "NL2179",
  "Cannot initialize ",
  "NL2185",
  "Duplicate member `",
  "NL2197",
  "Unknown function `",
  "NL2247",
  "Unknown property `",
  "NL2250",
  "` has no export `",
  "NL2311",
  "` has no member `",
  "NL2280",
  "Empty import list",
  "NL2200",
  "Module constant `",
  "NL2219",
  "Unknown builtin `",
  "NL2244",
  "Unsupported `new ",
  "NL2252",
  "` has no field `",
  "NL2065",
  "must be a string",
  "NL4006",
  "Unknown method `",
  "NL2249",
  "unknown option: ",
  "NL3008",
  "` is a generic ",
  "NL2316",
  "` requires two ",
  "NL2100",
  "Unknown class `",
  "NL2245",
  "Unknown field `",
  "NL2246",
  " must be named",
  "NL2018",
  "Cannot assign ",
  "NL2178",
  "Cannot infer `",
  "NL2301",
  "Cannot call `",
  "NL2182",
  "`: expected ",
  "NL2117",
  "Cannot push ",
  "NL2186",
]

/**
 * The WP33 portability rules (docs/wp33-round-trip.md section 5.2), matched by
 * substring against a `portability` message and against nothing else. A
 * retired row keeps its entry, as every retired rule does: NL8011's fragment
 * matches nothing now that no pass prints it, and its number stays reserved so
 * the band has no gap. `tests/wordings/unreachable.txt` names the retired rows
 * and why each went.
 */
const portabilityRules = (): string[] => [
  "overwrites the element a reference still reads, and TypeScript replaces the object instead",
  "NL8004",
  "is copied into the array here, and TypeScript stores the same object",
  "NL8003",
  "follows the native NaN and signed-zero rules here, not JavaScript's",
  "NL8010",
  "panics here outside its receiver's bounds, where TypeScript clamps",
  "NL8002",
  "prints a negative zero as 0 here, and Node's console prints -0",
  "NL8011",
  "wraps here, and TypeScript keeps counting past the range",
  "NL8007",
  "counts UTF-8 bytes here, and UTF-16 units in TypeScript",
  "NL8001",
  "is filled with zeros here, and with holes in TypeScript",
  "NL8005",
  "is a 64-bit integer here, and a double in TypeScript",
  "NL8009",
  "reads back signed here, and unsigned in TypeScript",
  "NL8008",
  "truncates here, and TypeScript divides exactly",
  "NL8006",
]

/** The WP15 section 8 rules, matched by substring: their message opens with a variable name. */
const performanceRules = (): string[] => [
  "--wrapping is deprecated and reaches only the modules of the entry package, never a dependency or the standard library: call `wrappingAdd`, `wrappingSub` and `wrappingMul` from `",
  "NL9015",
  "` but allocates on every call, so each thread marks and releases its arena around every element. Compute the answer without building a string, an array or an object to save both",
  "NL9012",
  "--unchecked-indexing is deprecated and reaches only the modules of the entry package, never a dependency or the standard library: call `uncheckedGet` and `uncheckedSet` from `",
  "NL9014",
  "so entering the range keeps its check on every iteration of this loop",
  "NL9013",
  "allocates a dynamically sized array on every iteration of this loop",
  "NL9001",
  "is rebuilt from its own value on every iteration of this loop",
  "NL9002",
  "are padding the alignment rules insert and nothing reads",
  "NL9010",
  "leaves arena memory behind on every pass of this loop",
  "NL9011",
  "already holds an allocation and this one drops it",
  "NL9003",
  "is computed in i32 and can overflow it before",
  "NL9005",
  "this computes with overflow: the result",
  "NL9006",
  "drops the one the pass before gave it",
  "NL9016",
  "is called here inside a loop and",
  "NL9008",
  "is not proven to be in range for",
  "NL9007",
  "is not provably within",
  "NL9009",
  "is at or beyond the",
  "NL9004",
]

/**
 * The deprecation rules, matched by substring against a `deprecation` message
 * and against nothing else: a call the language still compiles and is going
 * to take away. Each message opens with the name of what is deprecated.
 */
const deprecationRules = (): string[] => [
  "is undefined behaviour the compiler does not check. Bracket the work with `using a = arena()`, which releases on every exit of its block and refuses whatever would outlive it",
  "NL7001",
  " is unchecked only because of --unchecked-indexing, which is deprecated: ",
  "NL7002",
]

/** The code of the first fragment of one table that `text` contains, or `UNCODED`. */
const firstMatch = (rules: string[], text: string): string => {
  let i: i32 = 0
  while (i < rules.length) {
    if (text.indexOf(rules[i]) >= 0) {
      return rules[i + 1]
    }
    i = i + 2
  }
  return UNCODED
}

/**
 * The code for one diagnostic. `kind` is the word in the summary line
 * (`error`, `syntax error`, `performance`, `portability`, `deprecation`) and
 * `text` the message without its location prefix.
 */
export const codeFor = (kind: string, text: string): string => {
  if (kind === "syntax error") {
    return SYNTAX
  }
  if (kind === "performance") {
    return firstMatch(performanceRules(), text)
  }
  if (kind === "portability") {
    return firstMatch(portabilityRules(), text)
  }
  if (kind === "deprecation") {
    return firstMatch(deprecationRules(), text)
  }
  return firstMatch(diagnosticRules(), text)
}
